---
- name: Install packages with native package manager
  package:
    name:
      - "{{ shell }}"
      - "{{ terminal_emulator }}"
      - "git"
      - "gnupg2"
      - "{{ browser.application }}"
      - "gopass"
  become: yes

- name: Install stable channel software with Snap
  snap:
    name:
      - "{{ item }}"
  with_items:
    - "wonderwall"
    - "foliate"
  become: yes

- name: Install edge channel software with Snap
  snap:
    classic: yes
    channel: "edge"
    name:
      - "{{ item }}"
  with_items:
    - go
  become: yes

- name: Install classic confinement Snaps
  snap:
    classic: yes
    name:
      - "{{ item }}"
  with_items:
    - "{{ editor }}"
    - "microk8s"
    - "kata-containers"
    - "slack"
  become: yes

- name: Install software with pip
  pip:
    extra_args: "--user"
    executable: "/usr/bin/pip3"
    name:
      - "awscli"

- name: Download git-town
  get_url:
    url: "https://github.com/Originate/git-town/releases/download/{{ gittown_version }}/git-town-linux-amd64"
    dest: "{{ user_bin_dir }}/git-town"
    mode: '0550'

- name: Download Terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/tmp/terraform.zip"
    mode: '0550'

- name: Unzip terraform
  unarchive:
    src: "/tmp/terraform.zip"
    dest: "{{ user_bin_dir }}"
